# Generated by Django 3.2.16 on 2022-11-07 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+911111111111', max_length=20, region=None)),
                ('about_me', models.TextField(default='Tell Something About Yourself')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='OTHER', max_length=10)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('city', models.CharField(default='Bengaluru', max_length=180)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter_handle', models.CharField(blank=True, max_length=20)),
                ('facebook_handle', models.CharField(blank=True, max_length=20)),
                ('instagram_handle', models.CharField(blank=True, max_length=20)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='account.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
